// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqpihanzjnwnzrlunujn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxcGloYW56am53bnpybHVudWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjczMTAsImV4cCI6MjA2OTA0MzMxMH0.BrqqA_fVDdXDiJvHcQy4ehUjyqoPoElbF46xinQg94k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});